[package]
name = "scale-serialization"
description = "SCALE Serialization"
version = "0.8.0"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"
repository = "https://github.com/virto-network/scales"
license = "Apache-2.0"

[dependencies]
bytes = { version = "1.1.0", default-features = false }
scale-info = { version = "1.0.0", default-features = false, features = ["serde"] }
serde = { version = "1.0.130", default-features = false }
serde_json = { version = "1.0.68", default-features = false, optional = true }
codec = { version = "2.3.1", package = "parity-scale-codec", default-features = false, optional = true }

[features]
default = ["std", "codec", "json", "experimental-serializer"]
std = ["scale-info/std", "bytes/std"]
experimental-serializer = []
json = ["serde_json"]

[dev-dependencies]
anyhow = "1.0.44"
codec = { version = "2.3.1", package = "parity-scale-codec", features = ["derive"] }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.68", default-features = false, features = ["alloc"] }
